version: "3.9"
name: staff
networks:
  stylemate_net:
    external: true

services:
  staff_api:
    build:
      context: ./staff-api
      dockerfile: staff-api/Dockerfile
    container_name: staff_api
    restart: unless-stopped
    expose: ["80"]
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=stylemate_postgres;Port=5432;Database=stylemate;Username=postgres;Password=postgres123
      - JWT__Issuer=StyleMateAuth
      - JWT__Audience=StyleMateClients
      - JWT__SecretKey=YourSuperSecretKeyThatIsAtLeast256BitsLongForHmacSha256Signing
      - REDIS__CONNECTION=redis:6379
    networks:
      stylemate_net:
        aliases: [staff_api]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1/swagger/index.html || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  staff_ui_nginx:
    build: ./staff-ui
    container_name: staff_ui_nginx
    restart: unless-stopped
    expose: ["80"]
    networks:
      stylemate_net:
        aliases: [staff_ui_nginx]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/remoteEntry.js"]
      interval: 10s
      timeout: 3s
      retries: 5
