version: "3.9"
name: staff
networks:
  stylemate_net:
    external: true

services:
  staff_api:
    build:
      context: ./staff-api
      dockerfile: staff-api/Dockerfile
    container_name: staff_api
    restart: unless-stopped
    expose: ["80"]
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - REDIS__CONNECTION=redis:6379
    networks:
      stylemate_net:
        aliases: [staff_api]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/weatherforecast"]
      interval: 10s
      timeout: 3s
      retries: 5

  staff_ui_nginx:
    build: ./staff-ui
    container_name: staff_ui_nginx
    restart: unless-stopped
    expose: ["80"]
    networks:
      stylemate_net:
        aliases: [staff_ui_nginx]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/remoteEntry.js"]
      interval: 10s
      timeout: 3s
      retries: 5
